### ISSUE TITLE
Demo doesn't show any notifications.

### ISSUE THREAD

**Issue by codedust** [Martijnc/gowebpush#2]
The [Demo](https://playground.martijnc.be/web-push/) doen's show any notification in the latest version of Firefox (45.0.2) and Nightly (48.0a1).

**Comment by Martijnc** [comment]
The demo should work again in the latest nightly (49.0a1).

**Comment by codedust** [comment]
Hey! Thanks for looking after it! I can confirm it also works in Firefox 46.0. :tada:
